### ISSUE TITLE
Allow moving the grid by pressing spacebar and move the mouse around

### ISSUE THREAD

**Issue by Kaliph** [Krevo/geotrain#1]
Feature request:

It would be nice to be able to move the grid faster then with the current arrow keys.
If u press Spacebar and move the mouse around.... the grid will follow the mouse movement.

**Comment by Kaliph** [comment]
I have finished this feature. I will publish a pull request this weekend.

**Comment by Krevo** [comment]
Is it still usefull ? I have a branch "mouseWithoutClick" , have you tested it ?

It may be more user-friendly to move when the mouse pointer is on a border of the layout rather than clicking (old methode) or pressing yet another key (I know that I've too many key control and the track panel and the future "command" panel will enable to remove most of the existing key control)

**Comment by Krevo** [comment]
I close since I've merged "moveWithoutClick" branhc into master.

**Comment by Kaliph** [comment]
Hi Francois,

sorry was my first pull request. I will take more care next time. At the
moment I have to work on my project. So I have not much time to do the
tracklist. I can send u my progress if u are interested.

Best regards

François Crevola <notifications@github.com> schrieb am Mi. 10. Jan. 2018 um
19:19:

**Comment by Krevo** [comment]
No problem, take the time you need to work on you branch doing the track panel.

**Comment by Krevo** [comment]
..and don't worry for your first PR. I was just giving some advice to make things (like revuewing and testing) more easy.

**Comment by Kaliph** [comment]
That’s good thing. Only with feedback I can improve my work.... I will try
to get this trackpanel move the tracks. But it will take time. I need to
focus for now a bit on my other project with which I will try to found a
company soon. But I will let you know if I have something new to tell on
the trackpanel. BR

François Crevola <notifications@github.com> schrieb am Fr. 12. Jan. 2018 um
18:59:
